#ifndef STATUS_EFFECTS_H
#define STATUS_EFFECTS_H

#define NO_STATUS 0
#define TEMP_STATUS_MIMIC 1
#define TEMP_STATUS_SUBSTITUTE 2
#define TEMP_STATUS_TRANSFORMED 3
#define TEMP_STATUS_BOUND 4
#define TEMP_STATUS_CURSE 5
#define TEMP_STATUS_NIGHTMARE 6
#define TEMP_STATUS_PERISH_SONG 7
#define TEMP_STATUS_SEEDED 8
#define TEMP_STATUS_IDENTIFIED 9
#define TEMP_STATUS_MINIMIZE 10
#define TEMP_STATUS_AQUA_RING 11
#define TEMP_STATUS_ROOTING 12
#define TEMP_STATUS_TAKING_AIM 13
#define TEMP_STATUS_DROWSY 14
#define TEMP_STATUS_PRIMING 15
#define TEMP_STATUS_CHARGED 16
#define TEMP_STATUS_DEFENSE_CURL 17
#define TEMP_STATUS_CANT_ESCAPE 18
#define TEMP_STATUS_DISABLE 19
#define TEMP_STATUS_IMPRISON 20
#define TEMP_STATUS_TAUNT 21
#define TEMP_STATUS_TORMENT 22
#define TEMP_STATUS_CONFUSION 23
#define TEMP_STATUS_INFATUATION 24
#define TEMP_STATUS_FOCUS_ENERGY 25
#define TEMP_STATUS_CHOICE_LOCK 26
#define TEMP_STATUS_ENCORE 27
#define TEMP_STATUS_RAMPAGE 28
#define TEMP_STATUS_ROLLING 29
#define TEMP_STATUS_UPROAR 30
#define TEMP_STATUS_MULTI_TURN_MOVE 31
#define TEMP_STATUS_BIDE 32
#define TEMP_STATUS_RECHARGING 33
#define TEMP_STATUS_CHARGING_TURN 34
#define TEMP_STATUS_TRANSIENT 35
#define TEMP_STATUS_FLINCH 36
#define TEMP_STATUS_BRACING 37
#define TEMP_STATUS_CENTER_OF_ATTENTION 38
#define TEMP_STATUS_MAGIC_COAT 39
#define TEMP_STATUS_PROTECTION 40
#define TEMP_STATUS_FLY 41
#define TEMP_STATUS_DIG 42
#define TEMP_STATUS_DIVE 43
#define TEMP_STATUS_BOUNCE 44
#define TEMP_STATUS_SWITCHING 45
#define TEMP_STATUS_DAMAGED_THIS_TURN 46

//status effects that last after you switch
#define STATUS_PARALYSIS 2
#define STATUS_SLEEP 3
#define STATUS_POISON 4
#define STATUS_BURN 5
#define STATUS_FREEZE 6
#define STATUS_TOXIC 11

#endif